Chore: Run CI with latest NPM version
With the latest yeoman dependencies,  I was seeing errors under Node 12/14, unless NPM 7 was used to install dependencies:

- Uncaught Error: Cannot find module 'rimraf'
- Uncaught Error: Cannot find module 'mkdirp'